function xdot = fstatederivative(t, x)

% Define constants

% Define forces: 

% State assignments
q1 = x(1); q2 = x(2); q3 = x(3); q4 = x(4); q5 = x(5); 
u1 = x(6); u2 = x(7); u3 = x(8); u4 = x(9); u5 = x(10); 

c1 = cos(q1); s1 = sin(q1); 

MM = zeros(5,5); rhs = zeros(5,1);

% Mass Matrix
MM(1,1) = -2*q2*q3*msoftparallel + (mfoot + msoftparallel)*(q2*q2) + ...
msoftparallel*(q3*q3); MM(1,2) = 0; MM(1,3) = 0; MM(1,4) = ...
-(s1*(-(q3*msoftparallel) + q2*(mfoot + msoftparallel))); MM(1,5) = ...
c1*(-(q3*msoftparallel) + q2*(mfoot + msoftparallel)); 
MM(2,1) = MM(1,2); MM(2,2) = mfoot + msoftparallel; MM(2,3) = -msoftparallel; ...
MM(2,4) = c1*(mfoot + msoftparallel); MM(2,5) = s1*(mfoot + msoftparallel); 
MM(3,1) = MM(1,3); MM(3,2) = MM(2,3); MM(3,3) = msoftparallel; MM(3,4) = ...
-(c1*msoftparallel); MM(3,5) = -(s1*msoftparallel); 
MM(4,1) = MM(1,4); MM(4,2) = MM(2,4); MM(4,3) = MM(3,4); MM(4,4) = mfoot + ...
mpelvis + msoftparallel; MM(4,5) = 0; 
MM(5,1) = MM(1,5); MM(5,2) = MM(2,5); MM(5,3) = MM(3,5); MM(5,4) = MM(4,5); ...
MM(5,5) = mfoot + mpelvis + msoftparallel; 

% righthand side terms
rhs(1) = q3*msoftparallel*(2*u1*(u2 - u3) + g*cos(q1 - gslope)) - ...
q2*(2*u1*(-(u3*msoftparallel) + u2*(mfoot + msoftparallel)) + g*(mfoot + ...
msoftparallel)*cos(q1 - gslope)); 
rhs(2) = -(u2*cleg) + kleg*(-q2 + lleg) + (-(q3*msoftparallel) + q2*(mfoot + ...
msoftparallel))*(u1*u1) - g*mfoot*sin(q1 - gslope) - g*msoftparallel*sin(q1 - ...
gslope); 
rhs(3) = -(u3*csoftparallel) + ksoftparallel*(-q3 + lsoftparallel) + (-q2 + ...
q3)*msoftparallel*(u1*u1) + g*msoftparallel*sin(q1 - gslope); 
rhs(4) = 2*s1*u1*u2*mfoot + 2*s1*u1*u2*msoftparallel - ...
2*s1*u1*u3*msoftparallel - c1*q3*msoftparallel*(u1*u1) + c1*q2*(mfoot + ...
msoftparallel)*(u1*u1) + g*mfoot*sin(gslope) + g*mpelvis*sin(gslope) + ...
g*msoftparallel*sin(gslope); 
rhs(5) = -2*c1*u1*u2*mfoot - 2*c1*u1*u2*msoftparallel + ...
2*c1*u1*u3*msoftparallel - g*mfoot*cos(gslope) - g*mpelvis*cos(gslope) - ...
g*msoftparallel*cos(gslope) - q3*s1*msoftparallel*(u1*u1) + q2*s1*(mfoot + ...
msoftparallel)*(u1*u1); 

udot = MM\rhs;
xdot = [x(5+1:10); udot];

constraintJacobianStance(1,1) = -(q2*s1); constraintJacobianStance(1,2) = c1; ...
constraintJacobianStance(1,3) = 0; constraintJacobianStance(1,4) = 1; ...
constraintJacobianStance(1,5) = 0; 
constraintJacobianStance(2,1) = c1*q2; constraintJacobianStance(2,2) = s1; ...
constraintJacobianStance(2,3) = 0; constraintJacobianStance(2,4) = 0; ...
constraintJacobianStance(2,5) = 1; 


constraintJacobianStanceDot(1,1) = -(c1*q2*u1) - s1*u2; ...
constraintJacobianStanceDot(1,2) = -(s1*u1); constraintJacobianStanceDot(1,3) ...
= 0; constraintJacobianStanceDot(1,4) = 0; constraintJacobianStanceDot(1,5) = ...
0; 
constraintJacobianStanceDot(2,1) = -(q2*s1*u1) + c1*u2; ...
constraintJacobianStanceDot(2,2) = c1*u1; constraintJacobianStanceDot(2,3) = ...
0; constraintJacobianStanceDot(2,4) = 0; constraintJacobianStanceDot(2,5) = ...
0; 


constraintJacobianAerial(1,1) = 1; constraintJacobianAerial(1,2) = 0; ...
constraintJacobianAerial(1,3) = 0; constraintJacobianAerial(1,4) = 0; ...
constraintJacobianAerial(1,5) = 0; 
constraintJacobianAerial(2,1) = 0; constraintJacobianAerial(2,2) = 1; ...
constraintJacobianAerial(2,3) = 0; constraintJacobianAerial(2,4) = 0; ...
constraintJacobianAerial(2,5) = 0; 
constraintJacobianAerial(3,1) = 0; constraintJacobianAerial(3,2) = 0; ...
constraintJacobianAerial(3,3) = 1; constraintJacobianAerial(3,4) = 0; ...
constraintJacobianAerial(3,5) = 0; 


constraintJacobianAerialDot(1,1) = 0; constraintJacobianAerialDot(1,2) = 0; ...
constraintJacobianAerialDot(1,3) = 0; constraintJacobianAerialDot(1,4) = 0; ...
constraintJacobianAerialDot(1,5) = 0; 
constraintJacobianAerialDot(2,1) = 0; constraintJacobianAerialDot(2,2) = 0; ...
constraintJacobianAerialDot(2,3) = 0; constraintJacobianAerialDot(2,4) = 0; ...
constraintJacobianAerialDot(2,5) = 0; 
constraintJacobianAerialDot(3,1) = 0; constraintJacobianAerialDot(3,2) = 0; ...
constraintJacobianAerialDot(3,3) = 0; constraintJacobianAerialDot(3,4) = 0; ...
constraintJacobianAerialDot(3,5) = 0; 


kineticEnergy = (mpelvis*(u4*u4 + u5*u5) + mfoot*(-2*q2*u1*(s1*u4 - c1*u5) + ...
2*u2*(c1*u4 + s1*u5) + q2*q2*(u1*u1) + u2*u2 + u4*u4 + u5*u5) + ...
msoftparallel*(-2*(q2 - q3)*s1*u1*u4 + 2*s1*(u2 - u3)*u5 + c1*(2*(u2 - u3)*u4 ...
+ 2*(q2 - q3)*u1*u5) + (q2 - q3)*(q2 - q3)*(u1*u1) + (u2 - u3)*(u2 - u3) + ...
u4*u4 + u5*u5))/2.;

potentialEnergy = (kleg*((-q2 + lleg)*(-q2 + lleg)) + ksoftparallel*((-q3 + ...
lsoftparallel)*(-q3 + lsoftparallel)) + 2*g*mpelvis*(q5*cos(gslope) - ...
q4*sin(gslope)) - 2*g*mfoot*(-(q5*cos(gslope)) - q2*sin(q1 - gslope) + ...
q4*sin(gslope)) - 2*g*msoftparallel*(-(q5*cos(gslope)) - (q2 - q3)*sin(q1 - ...
gslope) + q4*sin(gslope)))/2.;

PEgrav = -(mpelvis*(-(q5*g*cos(gslope)) + q4*g*sin(gslope))) - ...
mfoot*(-(q5*g*cos(gslope)) - q2*g*sin(q1 - gslope) + q4*g*sin(gslope)) - ...
msoftparallel*(-(q5*g*cos(gslope)) - (q2 - q3)*g*sin(q1 - gslope) + ...
q4*g*sin(gslope));

PEspring = (kleg*((q2 - lleg)*(q2 - lleg)))/2. + (ksoftparallel*((q3 - ...
lsoftparallel)*(q3 - lsoftparallel)))/2.;

comvx = (c1*u2*mfoot + u4*mfoot + u4*mpelvis + q3*s1*u1*msoftparallel + ...
c1*u2*msoftparallel - c1*u3*msoftparallel + u4*msoftparallel - ...
q2*s1*u1*(mfoot + msoftparallel))*power(mfoot + mpelvis + msoftparallel,-1);

comvy = (u5*mfoot + u5*mpelvis + u5*msoftparallel + ...
c1*u1*(-(q3*msoftparallel) + q2*(mfoot + msoftparallel)) + ...
s1*(-(u3*msoftparallel) + u2*(mfoot + msoftparallel)))*power(mfoot + mpelvis ...
+ msoftparallel,-1);

points.foot(1) = c1*q2 + q4; 
points.foot(2) = q5 + q2*s1; 


points.pelvis(1) = q4; 
points.pelvis(2) = q5; 


points.COMpos(1) = c1*(q2*mfoot + (q2 - q3)*msoftparallel)*power(mfoot + ...
mpelvis + msoftparallel,-1) + (q4*mfoot + q4*mpelvis + ...
q4*msoftparallel)*power(mfoot + mpelvis + msoftparallel,-1); 
points.COMpos(2) = s1*(q2*mfoot + (q2 - q3)*msoftparallel)*power(mfoot + ...
mpelvis + msoftparallel,-1) + (q5*mfoot + q5*mpelvis + ...
q5*msoftparallel)*power(mfoot + mpelvis + msoftparallel,-1); 


points.softparallel(1) = c1*(q2 - q3) + q4; 
points.softparallel(2) = q5 + (q2 - q3)*s1; 


velJacobian(1,1) = 0; velJacobian(1,2) = 0; velJacobian(1,3) = 0; ...
velJacobian(1,4) = 1; velJacobian(1,5) = 0; 
velJacobian(2,1) = 0; velJacobian(2,2) = 0; velJacobian(2,3) = 0; ...
velJacobian(2,4) = 0; velJacobian(2,5) = 1; 
velJacobian(3,1) = -(q2*s1); velJacobian(3,2) = c1; velJacobian(3,3) = 0; ...
velJacobian(3,4) = 1; velJacobian(3,5) = 0; 
velJacobian(4,1) = c1*q2; velJacobian(4,2) = s1; velJacobian(4,3) = 0; ...
velJacobian(4,4) = 0; velJacobian(4,5) = 1; 
velJacobian(5,1) = -(q2*s1) + q3*s1; velJacobian(5,2) = c1; velJacobian(5,3) ...
= -c1; velJacobian(5,4) = 1; velJacobian(5,5) = 0; 
velJacobian(6,1) = c1*q2 - c1*q3; velJacobian(6,2) = s1; velJacobian(6,3) = ...
-s1; velJacobian(6,4) = 0; velJacobian(6,5) = 1; 

